// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: protobuf/School.proto

package school_protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	FirstExam      int32                  `protobuf:"varint,4,opt,name=firstExam,proto3" json:"firstExam,omitempty"`
	SecondExam     int32                  `protobuf:"varint,5,opt,name=secondExam,proto3" json:"secondExam,omitempty"`
	ThirdExam      int32                  `protobuf:"varint,6,opt,name=thirdExam,proto3" json:"thirdExam,omitempty"`
	AsignmentScore int32                  `protobuf:"varint,7,opt,name=asignmentScore,proto3" json:"asignmentScore,omitempty"`
	FinalScore     int32                  `protobuf:"varint,8,opt,name=finalScore,proto3" json:"finalScore,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StudentRequest) Reset() {
	*x = StudentRequest{}
	mi := &file_protobuf_School_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentRequest) ProtoMessage() {}

func (x *StudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_School_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentRequest.ProtoReflect.Descriptor instead.
func (*StudentRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_School_proto_rawDescGZIP(), []int{0}
}

func (x *StudentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *StudentRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *StudentRequest) GetFirstExam() int32 {
	if x != nil {
		return x.FirstExam
	}
	return 0
}

func (x *StudentRequest) GetSecondExam() int32 {
	if x != nil {
		return x.SecondExam
	}
	return 0
}

func (x *StudentRequest) GetThirdExam() int32 {
	if x != nil {
		return x.ThirdExam
	}
	return 0
}

func (x *StudentRequest) GetAsignmentScore() int32 {
	if x != nil {
		return x.AsignmentScore
	}
	return 0
}

func (x *StudentRequest) GetFinalScore() int32 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

type StudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	FinalScore    int32                  `protobuf:"varint,2,opt,name=finalScore,proto3" json:"finalScore,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentResponse) Reset() {
	*x = StudentResponse{}
	mi := &file_protobuf_School_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentResponse) ProtoMessage() {}

func (x *StudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_School_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentResponse.ProtoReflect.Descriptor instead.
func (*StudentResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_School_proto_rawDescGZIP(), []int{1}
}

func (x *StudentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StudentResponse) GetFinalScore() int32 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

type StudentScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Exam          int32                  `protobuf:"varint,2,opt,name=exam,proto3" json:"exam,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentScoreRequest) Reset() {
	*x = StudentScoreRequest{}
	mi := &file_protobuf_School_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentScoreRequest) ProtoMessage() {}

func (x *StudentScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_School_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentScoreRequest.ProtoReflect.Descriptor instead.
func (*StudentScoreRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_School_proto_rawDescGZIP(), []int{2}
}

func (x *StudentScoreRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentScoreRequest) GetExam() int32 {
	if x != nil {
		return x.Exam
	}
	return 0
}

func (x *StudentScoreRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type StudentFinalScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentFinalScoreRequest) Reset() {
	*x = StudentFinalScoreRequest{}
	mi := &file_protobuf_School_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentFinalScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentFinalScoreRequest) ProtoMessage() {}

func (x *StudentFinalScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_School_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentFinalScoreRequest.ProtoReflect.Descriptor instead.
func (*StudentFinalScoreRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_School_proto_rawDescGZIP(), []int{3}
}

func (x *StudentFinalScoreRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_protobuf_School_proto protoreflect.FileDescriptor

const file_protobuf_School_proto_rawDesc = "" +
	"\n" +
	"\x15protobuf/School.proto\x12\x04data\"\xfe\x01\n" +
	"\x0eStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12\x1c\n" +
	"\tfirstExam\x18\x04 \x01(\x05R\tfirstExam\x12\x1e\n" +
	"\n" +
	"secondExam\x18\x05 \x01(\x05R\n" +
	"secondExam\x12\x1c\n" +
	"\tthirdExam\x18\x06 \x01(\x05R\tthirdExam\x12&\n" +
	"\x0easignmentScore\x18\a \x01(\x05R\x0easignmentScore\x12\x1e\n" +
	"\n" +
	"finalScore\x18\b \x01(\x05R\n" +
	"finalScore\"I\n" +
	"\x0fStudentResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"finalScore\x18\x02 \x01(\x05R\n" +
	"finalScore\"O\n" +
	"\x13StudentScoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04exam\x18\x02 \x01(\x05R\x04exam\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"*\n" +
	"\x18StudentFinalScoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xde\x01\n" +
	"\x06School\x12;\n" +
	"\n" +
	"AddStudent\x12\x14.data.StudentRequest\x1a\x15.data.StudentResponse\"\x00\x12G\n" +
	"\x11AddScoreOfStudent\x12\x19.data.StudentScoreRequest\x1a\x15.data.StudentResponse\"\x00\x12N\n" +
	"\x13calculateFinalScore\x12\x1e.data.StudentFinalScoreRequest\x1a\x15.data.StudentResponse\"\x00B/Z-github.com/82595-jorge-capellan/school_protosb\x06proto3"

var (
	file_protobuf_School_proto_rawDescOnce sync.Once
	file_protobuf_School_proto_rawDescData []byte
)

func file_protobuf_School_proto_rawDescGZIP() []byte {
	file_protobuf_School_proto_rawDescOnce.Do(func() {
		file_protobuf_School_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_School_proto_rawDesc), len(file_protobuf_School_proto_rawDesc)))
	})
	return file_protobuf_School_proto_rawDescData
}

var file_protobuf_School_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_School_proto_goTypes = []any{
	(*StudentRequest)(nil),           // 0: data.StudentRequest
	(*StudentResponse)(nil),          // 1: data.StudentResponse
	(*StudentScoreRequest)(nil),      // 2: data.StudentScoreRequest
	(*StudentFinalScoreRequest)(nil), // 3: data.StudentFinalScoreRequest
}
var file_protobuf_School_proto_depIdxs = []int32{
	0, // 0: data.School.AddStudent:input_type -> data.StudentRequest
	2, // 1: data.School.AddScoreOfStudent:input_type -> data.StudentScoreRequest
	3, // 2: data.School.calculateFinalScore:input_type -> data.StudentFinalScoreRequest
	1, // 3: data.School.AddStudent:output_type -> data.StudentResponse
	1, // 4: data.School.AddScoreOfStudent:output_type -> data.StudentResponse
	1, // 5: data.School.calculateFinalScore:output_type -> data.StudentResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_School_proto_init() }
func file_protobuf_School_proto_init() {
	if File_protobuf_School_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_School_proto_rawDesc), len(file_protobuf_School_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_School_proto_goTypes,
		DependencyIndexes: file_protobuf_School_proto_depIdxs,
		MessageInfos:      file_protobuf_School_proto_msgTypes,
	}.Build()
	File_protobuf_School_proto = out.File
	file_protobuf_School_proto_goTypes = nil
	file_protobuf_School_proto_depIdxs = nil
}
